### ISSUE TITLE
Syntax highlighting does not consider comments with #

### ISSUE THREAD

**Issue by vitorgalvao** [textmate/applescript.tmbundle#11]
With AppleScript, you can comment in three different ways:

* With two hyphens.
* Enclosed in parenthesis asterisk, for multi-line comments.
* With a hash.

With this bundle, however, comments starting with a hash sign are not correctly coloured, appearing as if they were code to be interpreted.

See [this gist](https://gist.github.com/anonymous/4846a3510c3533dee479924004604ecd) for an example.

![image](https://cloud.githubusercontent.com/assets/1699443/21482929/656763d6-cb72-11e6-9f29-e8428554b665.png)

Those happen on GitHub itself, and they informed me that since they pull the grammar from here, I should make here the report.

**Comment by infininight** [comment]
Fixed, thanks. Note that Github will take 4-6 weeks to deploy this change.
