### ISSUE TITLE
`decompile_as` is 32 bit

### ISSUE THREAD

**Issue by doekman** [textmate/applescript.tmbundle#12]
It seems the command [decompile_as](https://github.com/textmate/applescript.tmbundle/blob/df46dd96d877c5d2aadef4267c950e92a35425fa/Commands/Decompile%20AppleScript.tmCommand#L9) is still 32-bit: 

Determined with the following command [from Rich Trouton's tweet](https://twitter.com/rtrouton/status/1130482310762115072):

    mdfind "kMDItemExecutableArchitectures == '*i386*' && kMDItemExecutableArchitectures != '*x86*'"

BTW: the command can be replaced with `osadecompile` (`osadecompile` itself is introduced in OS X 10.5 (https://developer.apple.com/library/content/releasenotes/AppleScript/RN-AppleScript/RN-10_5/RN-10_5.html#//apple_ref/doc/uid/TP40000982-CH105-SW1). `osacompile` was available in OS X 10.0 initially.)

(I've emailed in october 2017 about this with Michael Sheets via <tm-support@macromates.com>)

**Comment by sorbits** [comment]
Sorry about the late response, I wasn’t watching this repository and I think @infininight forgot to ask me about it :)
